// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/finance.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CoinFinanceRequest struct {
	Coin                 string   `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	StartTime            uint32   `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              uint32   `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoinFinanceRequest) Reset()         { *m = CoinFinanceRequest{} }
func (m *CoinFinanceRequest) String() string { return proto.CompactTextString(m) }
func (*CoinFinanceRequest) ProtoMessage()    {}
func (*CoinFinanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_06254c136940ed93, []int{0}
}

func (m *CoinFinanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoinFinanceRequest.Unmarshal(m, b)
}
func (m *CoinFinanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoinFinanceRequest.Marshal(b, m, deterministic)
}
func (m *CoinFinanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinFinanceRequest.Merge(m, src)
}
func (m *CoinFinanceRequest) XXX_Size() int {
	return xxx_messageInfo_CoinFinanceRequest.Size(m)
}
func (m *CoinFinanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinFinanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CoinFinanceRequest proto.InternalMessageInfo

func (m *CoinFinanceRequest) GetCoin() string {
	if m != nil {
		return m.Coin
	}
	return ""
}

func (m *CoinFinanceRequest) GetStartTime() uint32 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *CoinFinanceRequest) GetEndTime() uint32 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type CoinFinanceReply struct {
	FinanceList          []*FinanceItem `protobuf:"bytes,1,rep,name=finance_list,json=financeList,proto3" json:"finance_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CoinFinanceReply) Reset()         { *m = CoinFinanceReply{} }
func (m *CoinFinanceReply) String() string { return proto.CompactTextString(m) }
func (*CoinFinanceReply) ProtoMessage()    {}
func (*CoinFinanceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_06254c136940ed93, []int{1}
}

func (m *CoinFinanceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoinFinanceReply.Unmarshal(m, b)
}
func (m *CoinFinanceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoinFinanceReply.Marshal(b, m, deterministic)
}
func (m *CoinFinanceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinFinanceReply.Merge(m, src)
}
func (m *CoinFinanceReply) XXX_Size() int {
	return xxx_messageInfo_CoinFinanceReply.Size(m)
}
func (m *CoinFinanceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinFinanceReply.DiscardUnknown(m)
}

var xxx_messageInfo_CoinFinanceReply proto.InternalMessageInfo

func (m *CoinFinanceReply) GetFinanceList() []*FinanceItem {
	if m != nil {
		return m.FinanceList
	}
	return nil
}

type FinanceItem struct {
	CoinKey              string   `protobuf:"bytes,1,opt,name=coin_key,json=coinKey,proto3" json:"coin_key,omitempty"`
	SmallIn              float64  `protobuf:"fixed64,2,opt,name=small_in,json=smallIn,proto3" json:"small_in,omitempty"`
	MiddleIn             float64  `protobuf:"fixed64,3,opt,name=middle_in,json=middleIn,proto3" json:"middle_in,omitempty"`
	BigIn                float64  `protobuf:"fixed64,4,opt,name=big_in,json=bigIn,proto3" json:"big_in,omitempty"`
	SuperIn              float64  `protobuf:"fixed64,5,opt,name=super_in,json=superIn,proto3" json:"super_in,omitempty"`
	SmallOut             float64  `protobuf:"fixed64,6,opt,name=small_out,json=smallOut,proto3" json:"small_out,omitempty"`
	MiddleOut            float64  `protobuf:"fixed64,7,opt,name=middle_out,json=middleOut,proto3" json:"middle_out,omitempty"`
	BigOut               float64  `protobuf:"fixed64,8,opt,name=big_out,json=bigOut,proto3" json:"big_out,omitempty"`
	SuperOut             float64  `protobuf:"fixed64,9,opt,name=super_out,json=superOut,proto3" json:"super_out,omitempty"`
	FinanceDate          uint32   `protobuf:"varint,10,opt,name=finance_date,json=financeDate,proto3" json:"finance_date,omitempty"`
	UpdateTime           uint32   `protobuf:"varint,11,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinanceItem) Reset()         { *m = FinanceItem{} }
func (m *FinanceItem) String() string { return proto.CompactTextString(m) }
func (*FinanceItem) ProtoMessage()    {}
func (*FinanceItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_06254c136940ed93, []int{2}
}

func (m *FinanceItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinanceItem.Unmarshal(m, b)
}
func (m *FinanceItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinanceItem.Marshal(b, m, deterministic)
}
func (m *FinanceItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinanceItem.Merge(m, src)
}
func (m *FinanceItem) XXX_Size() int {
	return xxx_messageInfo_FinanceItem.Size(m)
}
func (m *FinanceItem) XXX_DiscardUnknown() {
	xxx_messageInfo_FinanceItem.DiscardUnknown(m)
}

var xxx_messageInfo_FinanceItem proto.InternalMessageInfo

func (m *FinanceItem) GetCoinKey() string {
	if m != nil {
		return m.CoinKey
	}
	return ""
}

func (m *FinanceItem) GetSmallIn() float64 {
	if m != nil {
		return m.SmallIn
	}
	return 0
}

func (m *FinanceItem) GetMiddleIn() float64 {
	if m != nil {
		return m.MiddleIn
	}
	return 0
}

func (m *FinanceItem) GetBigIn() float64 {
	if m != nil {
		return m.BigIn
	}
	return 0
}

func (m *FinanceItem) GetSuperIn() float64 {
	if m != nil {
		return m.SuperIn
	}
	return 0
}

func (m *FinanceItem) GetSmallOut() float64 {
	if m != nil {
		return m.SmallOut
	}
	return 0
}

func (m *FinanceItem) GetMiddleOut() float64 {
	if m != nil {
		return m.MiddleOut
	}
	return 0
}

func (m *FinanceItem) GetBigOut() float64 {
	if m != nil {
		return m.BigOut
	}
	return 0
}

func (m *FinanceItem) GetSuperOut() float64 {
	if m != nil {
		return m.SuperOut
	}
	return 0
}

func (m *FinanceItem) GetFinanceDate() uint32 {
	if m != nil {
		return m.FinanceDate
	}
	return 0
}

func (m *FinanceItem) GetUpdateTime() uint32 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func init() {
	proto.RegisterType((*CoinFinanceRequest)(nil), "proto.CoinFinanceRequest")
	proto.RegisterType((*CoinFinanceReply)(nil), "proto.CoinFinanceReply")
	proto.RegisterType((*FinanceItem)(nil), "proto.FinanceItem")
}

func init() { proto.RegisterFile("proto/finance.proto", fileDescriptor_06254c136940ed93) }

var fileDescriptor_06254c136940ed93 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xdf, 0x4a, 0xf3, 0x40,
	0x10, 0xc5, 0xbf, 0xf4, 0x5f, 0x9a, 0xc9, 0xa7, 0xc8, 0x8a, 0x34, 0x55, 0xc4, 0x9a, 0xab, 0x5e,
	0x55, 0xa8, 0xf8, 0x04, 0x4a, 0x25, 0x28, 0x88, 0xc1, 0xfb, 0x90, 0x34, 0x63, 0x59, 0x4c, 0x36,
	0x31, 0xd9, 0x5c, 0xe4, 0x0d, 0x7d, 0x2c, 0x99, 0xd9, 0x15, 0x2b, 0x7a, 0x95, 0xcc, 0xfc, 0x86,
	0x73, 0x86, 0x33, 0x0b, 0xc7, 0x75, 0x53, 0xe9, 0xea, 0xea, 0x55, 0xaa, 0x54, 0x6d, 0x71, 0xc5,
	0x95, 0x18, 0xf3, 0x27, 0xcc, 0x40, 0xdc, 0x56, 0x52, 0x6d, 0x0c, 0x8b, 0xf1, 0xbd, 0xc3, 0x56,
	0x0b, 0x01, 0xa3, 0x6d, 0x25, 0x55, 0xe0, 0x2c, 0x9c, 0xa5, 0x17, 0xf3, 0xbf, 0x38, 0x07, 0x68,
	0x75, 0xda, 0xe8, 0x44, 0xcb, 0x12, 0x83, 0xc1, 0xc2, 0x59, 0x1e, 0xc4, 0x1e, 0x77, 0x5e, 0x64,
	0x89, 0x62, 0x0e, 0x53, 0x54, 0xb9, 0x81, 0x43, 0x86, 0x2e, 0xaa, 0x9c, 0x50, 0x18, 0xc1, 0xd1,
	0x0f, 0x8f, 0xba, 0xe8, 0xc5, 0x0d, 0xfc, 0xb7, 0xfb, 0x24, 0x85, 0x6c, 0x75, 0xe0, 0x2c, 0x86,
	0x4b, 0x7f, 0x2d, 0xcc, 0x72, 0x2b, 0x3b, 0x1a, 0x69, 0x2c, 0x63, 0xdf, 0xce, 0x3d, 0xca, 0x56,
	0x87, 0x1f, 0x03, 0xf0, 0xf7, 0x20, 0xb9, 0xd2, 0x72, 0xc9, 0x1b, 0xf6, 0x76, 0x59, 0x97, 0xea,
	0x07, 0xec, 0x09, 0xb5, 0x65, 0x5a, 0x14, 0x89, 0x54, 0xbc, 0xad, 0x13, 0xbb, 0x5c, 0x47, 0x4a,
	0x9c, 0x81, 0x57, 0xca, 0x3c, 0x2f, 0x90, 0xd8, 0x90, 0xd9, 0xd4, 0x34, 0x22, 0x25, 0x4e, 0x60,
	0x92, 0xc9, 0x1d, 0x91, 0x11, 0x93, 0x71, 0x26, 0x77, 0x91, 0x62, 0xb9, 0xae, 0xc6, 0x86, 0xc0,
	0xd8, 0xca, 0x51, 0x6d, 0xe4, 0x8c, 0x53, 0xd5, 0xe9, 0x60, 0x62, 0xe4, 0xb8, 0xf1, 0xd4, 0x69,
	0x8a, 0xcd, 0x7a, 0x11, 0x75, 0x99, 0x5a, 0x77, 0xc2, 0x33, 0x70, 0xc9, 0x8d, 0xd8, 0x94, 0x19,
	0x99, 0x13, 0x20, 0x51, 0xf6, 0x23, 0xe4, 0x59, 0x51, 0x6a, 0x10, 0xbc, 0xfc, 0x4e, 0x2f, 0x4f,
	0x35, 0x06, 0xc0, 0x81, 0x7f, 0x25, 0x75, 0x97, 0x6a, 0x14, 0x17, 0xe0, 0x77, 0x35, 0x41, 0x73,
	0x12, 0x9f, 0x27, 0xc0, 0xb4, 0xe8, 0x2a, 0xeb, 0x67, 0x70, 0x6d, 0x92, 0x62, 0x03, 0x87, 0xf7,
	0xa8, 0xf7, 0x6e, 0x24, 0xe6, 0xf6, 0x10, 0xbf, 0xdf, 0xc6, 0xe9, 0xec, 0x2f, 0x54, 0x17, 0x7d,
	0xf8, 0x2f, 0x9b, 0x30, 0xb9, 0xfe, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x18, 0xb0, 0xc7, 0x0f, 0x71,
	0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FinanceClient is the client API for Finance service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FinanceClient interface {
	GetCoinFinance(ctx context.Context, in *CoinFinanceRequest, opts ...grpc.CallOption) (*CoinFinanceReply, error)
}

type financeClient struct {
	cc *grpc.ClientConn
}

func NewFinanceClient(cc *grpc.ClientConn) FinanceClient {
	return &financeClient{cc}
}

func (c *financeClient) GetCoinFinance(ctx context.Context, in *CoinFinanceRequest, opts ...grpc.CallOption) (*CoinFinanceReply, error) {
	out := new(CoinFinanceReply)
	err := c.cc.Invoke(ctx, "/proto.Finance/GetCoinFinance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinanceServer is the server API for Finance service.
type FinanceServer interface {
	GetCoinFinance(context.Context, *CoinFinanceRequest) (*CoinFinanceReply, error)
}

func RegisterFinanceServer(s *grpc.Server, srv FinanceServer) {
	s.RegisterService(&_Finance_serviceDesc, srv)
}

func _Finance_GetCoinFinance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoinFinanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinanceServer).GetCoinFinance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Finance/GetCoinFinance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinanceServer).GetCoinFinance(ctx, req.(*CoinFinanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Finance_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Finance",
	HandlerType: (*FinanceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCoinFinance",
			Handler:    _Finance_GetCoinFinance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/finance.proto",
}
