title = "ticker-gRPC-server"
config_version = 1

[mysql]
    server = "x.x.x.x"
    port = "3306"
    user = "root"
    password = "root"
    default_database = "abc"
[redis]
    server = "localhost"
    port = "6379"
    password = "123456"
